### ISSUE TITLE
Exclude searching for packages from a package source

### ISSUE THREAD

**Issue by rbdavison** [NuGet/PackageSourceMapper#42]
It would be useful to explicitly exclude searching for packages from a package source.
As an for example:
- Artificial Baked Cheese Inc. does some secret squirrel work on nut flavored cheese with special software to drive the process
- All corporate packages are named ABC.*
- They only want searches for corporate packages to be made against my corporate NuGet server https://nuget.abc.com/
- They want to prohibit searches for corporate packages being directed to nuget.org since the existence of the packages could give away meta data used by potential competitors on the structure of the corporate code and thus the secret processes
- They don't want to reinvent the wheel and thus want to get access to all the publicly available packages on NuGet.org

Perhaps a configuration like the following could be used
```
<packageSourceMapping>
  <clear />
  <packageSource key="nuget.abc.com">
    <package pattern="abc.*" />
  </packageSource>
  <packageSource key="nuget.org">
    <package excludePattern="abc.*" />
    <package pattern="*" />
  </packageSource>
</packageSourceMapping>
```

**Comment by zivkan** [comment]
@rbdavison this repo is for a tool that helps create a nuget.config with appropriate package source mapping. Discussions of the NuGet feature itself should go in NuGet/Home.

Perhaps it's not sufficiently clear, if so, maybe you could create a PR to suggest easier to understand wording, but according to the docs: https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping#package-pattern-precedence

>  For package prefix patterns, the longest has precedence.

In other words, since `abc.*` is longer than `*`, this means that package `abc.def` will only search sources that specify the `abc.*` prefix, and other sources will not be used.

If there's a package ID, or prefix, you'd like to query multiple sources for, the exact prefix needs to be specified in each source's mapping. For example, say xunit.* is cached on nuget.abc.com for performance/bandwidth reasons, then you'd need to do this:

```xml
<packageSourceMapping>
  <clear />
  <packageSource key="nuget.abc.com">
    <package pattern="abc.*" />
    <package pattern="xunit.*" />
  </packageSource>
  <packageSource key="nuget.org">
    <package pattern="*" />
    <package pattern="xunit.*" />
  </packageSource>
</packageSourceMapping>
```

Even though `xunit.*` is a subset of `*`, since NuGet only matches the longest prefix, both are needed for the nuget.org source since that prefix is used in another source. If nuget.org only had the `*` pattern, then `xunit.*` packages would only come from `nuget.abc.com` since that would be the longest matching prefix in the mapping.
